#!/usr/bin/env python3
"""Generate the assess skill's `references/levels.md` from `core/levels.py`.

The model reads the Markdown; `verify` and the CLI read the Python. Writing the
Markdown by hand would guarantee they drift, and drift here is invisible — the
workflow would quietly calibrate to numbers the verifier does not check against.
So the table is generated, and `--check` fails CI when it is stale.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "src"))

from fsa_trainer_skills.skills.assess.core import levels as L  # noqa: E402

TARGET = (
    ROOT
    / "src"
    / "fsa_trainer_skills"
    / "skills"
    / "assess"
    / "payload"
    / "fsa-assess"
    / "references"
    / "levels.md"
)

HEADER = """# Levels

Every assessment is calibrated for exactly one level. It is a required Step 0
input, and it changes the Bloom mix, the difficulty mix, the duration, how much
of the specification is handed over, and how strict the rubric is.

Two axes, because they answer different questions:

- **UP_SKILL** — same technology stack, greater depth. The candidate already
  works in this stack; the assessment probes how far.
- **RE_SKILL** — an experienced engineer arriving from a *different* stack.
  Transferable reasoning is high but stack-specific recall is not assumed, so
  these assessments use migration, integration, and modernisation framing and
  never reward knowing an idiom by heart.

`CPL` and `FR` have no bands. `UP_SKILL` and `RE_SKILL` each split into
`junior` / `mid` / `senior`.

The level goes in the display code and a `Level:` banner line — **never in the
filename stem**, which would break rubric discovery and the submission archive
naming the grading pipeline depends on.

> These are defaults. Confirm them with the user in Step 0 and adjust when the
> subject warrants it; state any deviation in the plan echo. `fsa-trainer-skills assess verify`
> reports drift from the level default as a warning, not an error.

<!-- Generated by scripts/assess/gen_levels_md.py from
     src/fsa_trainer_skills/skills/assess/core/levels.py.
     Do not edit by hand; edit the Python and regenerate. -->

## At a glance

"""


def render() -> str:
    lines = [HEADER.rstrip("\n"), ""]

    bloom_cols = " | ".join(name[:2] for name in L.BLOOM_ORDER)
    difficulty_cols = " | ".join(L.DIFFICULTY_ORDER)
    lines.append(f"| Level | Audience | {bloom_cols} | {difficulty_cols} | Tasks | Duration |")
    numeric = len(L.BLOOM_ORDER) + len(L.DIFFICULTY_ORDER)
    lines.append("|---|---|" + "---:|" * numeric + "---:|---:|")
    for level in L.LEVELS:
        bloom = " | ".join(str(level.bloom.get(name, 0)) for name in L.BLOOM_ORDER)
        difficulty = " | ".join(str(level.difficulty.get(name, 0)) for name in L.DIFFICULTY_ORDER)
        tasks = f"{level.task_range[0]}-{level.task_range[1]}"
        lines.append(
            f"| **{level.display}** | {level.audience} | {bloom} | {difficulty} | "
            f"{tasks} | {level.duration_factor}x |"
        )

    lines.append("")
    lines.append(
        f"Bloom columns are {', '.join(L.BLOOM_ORDER)}, as percentages of the question set. "
        "Duration is a multiplier on the baseline you would set for a fresher."
    )
    lines.append("")
    lines.append("## Per level")
    lines.append("")

    for level in L.LEVELS:
        lines.append(f"### {level.display}")
        lines.append("")
        lines.append(f"- **Audience** — {level.audience}")
        lines.append(f"- **Scope** — {level.scope}")
        lines.append(f"- **Rubric posture** — {level.rubric_posture}")
        lines.append(
            "- **Mechanisms** — "
            + (
                "may be named directly in the brief"
                if level.may_name_mechanism
                else "state the outcome and let the candidate choose the mechanism; "
                "the rubric still names it so criteria stay observable"
            )
        )
        seconds = ", ".join(
            f"{name} {level.time_map[name]}s"
            for name in L.DIFFICULTY_ORDER
            if name in level.time_map
        )
        lines.append(f"- **Seconds per question** — {seconds} (quiz always uses 5/10/20)")
        if level.notes:
            lines.append(f"- **Note** — {level.notes}")
        lines.append("")

    lines.append("## Question counts")
    lines.append("")
    lines.append(
        "Percentages become whole questions by largest remainder, so the counts always "
        "sum to the requested total. Ask the CLI rather than doing the arithmetic:"
    )
    lines.append("")
    lines.append("```bash")
    lines.append("fsa-trainer-skills assess levels show --level UP_SKILL --band mid --count 40")
    lines.append("```")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the file is stale")
    args = parser.parse_args()

    content = render()
    current = TARGET.read_text(encoding="utf-8") if TARGET.is_file() else ""

    if args.check:
        if current != content:
            print(f"ERROR: {TARGET.relative_to(ROOT)} is out of date", file=sys.stderr)
            print("run `python scripts/gen_levels_md.py` to regenerate", file=sys.stderr)
            return 1
        print("levels.md is up to date")
        return 0

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(content, encoding="utf-8")
    print(f"wrote {TARGET.relative_to(ROOT)} ({len(L.LEVELS)} levels)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
