#!/usr/bin/env python3
"""Generate the material skill's `references/structure.md` from `core/grammar.py`.

The model writes documents from this file; `verify` checks them against the
Python. Prose describing a required section the checker does not enforce would
calibrate the model to a constraint nothing holds it to — and prose omitting one
it does enforce produces documents that fail a check the docs never mentioned.
So the templates and the rulebook are both generated, and `--check` fails CI
when either is stale.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "src"))

from get_fsa_training_done.skills.material.core import grammar as G  # noqa: E402
from get_fsa_training_done.skills.material.core import rules as R  # noqa: E402

TARGET = (
    ROOT
    / "src"
    / "get_fsa_training_done"
    / "skills"
    / "material"
    / "payload"
    / "fsa-training-material"
    / "references"
    / "structure.md"
)

HEADER = """# Document structure

What each kind of teaching document is shaped like, and every rule
`FSA material verify` applies. Both come from the same definitions the checker
executes, so nothing here is a constraint the tool does not enforce.

**Write new lecture notes as a unit.** The chapter form is older, still used by
two modules, and is recognised so those files can be checked rather than
rewritten — not because it is a choice for new work.

Universal, whatever the kind:

- Exactly one `#` heading, on line 1. No YAML front matter.
- Every fenced block declares a language. `text` is the right tag for the blocks
  that are not code — diagrams, console output, directory trees.
- Relative links resolve, and so do their `#anchors`.
- English, unless the filename ends `_vn` to mark a translation.

<!-- Generated by scripts/material/gen_structure_md.py from
     src/get_fsa_training_done/skills/material/core/{grammar,rules}.py.
     Do not edit by hand; edit the Python and regenerate. -->
"""


def render() -> str:
    lines = [HEADER, "\n## Naming\n"]
    lines.append(f"- Lecture notes, handbooks and appendices: `{G.NOTE_FILENAME.pattern}`")
    lines.append(f"- Lab guides: `{G.LAB_FILENAME.pattern}`")
    lines.append(f"- Index `{G.HANDBOOK_INDEX}` is the module handbook.")
    lines.append(f"- Index `{G.APPENDIX_INDEX}` is the module appendix.")
    lines.append(
        "- A trailing letter marks an aside outside the syllabus (`02b_...`).\n"
        f"- A translation appends `{G.TRANSLATION_SUFFIX}` to the stem.\n"
    )

    for template in G.TEMPLATES:
        lines.append(f"\n## {template.title}\n")
        lines.append(f"{template.summary}\n")
        if template.numbered_sections:
            lines.append(
                "Sections between the opening and the closing ones are numbered "
                "`1..n`, contiguously, and named by the author.\n"
            )
        if template.slots:
            lines.append("| Section | Required | Holds |")
            lines.append("|---|---|---|")
            for slot in template.slots:
                required = "yes" if slot.required else "optional"
                lines.append(f"| `## {slot.label}` | {required} | {slot.description} |")
            lines.append("")
            for slot in template.slots:
                if slot.opening is not None:
                    lines.append(
                        f"`## {slot.label}` must open with `{slot.opening.pattern.lstrip('^')}`.\n"
                    )
        if template.footer_description:
            lines.append(f"Ends with {template.footer_description}\n")

    lines.append("\n## Fence languages\n")
    lines.append(
        "Anything outside this set is reported as a warning rather than an "
        "error — a module may legitimately introduce a language.\n"
    )
    lines.append(", ".join(f"`{name}`" for name in G.FENCE_LANGUAGES) + "\n")

    for scope, title, blurb in (
        ("document", "Rules — one document", "Applied to every file `verify` reads."),
        (
            "coverage",
            "Rules — material against the session plan",
            "Applied by `coverage`, comparing a folder with the plan that asks for it.",
        ),
    ):
        in_scope = [rule for rule in R.RULES if rule.scope == scope]
        lines.append(f"\n## {title}\n")
        lines.append(f"{blurb}\n")
        lines.append("| Rule | Severity | Checks |")
        lines.append("|---|---|---|")
        for rule in in_scope:
            lines.append(f"| `{rule.id}` | {rule.severity} | {rule.title} |")
        lines.append("")
        for rule in in_scope:
            lines.append(f"### `{rule.id}` — {rule.title}\n")
            lines.append(f"{rule.rationale}\n")

    counts = {
        severity: sum(1 for rule in R.RULES if rule.severity == severity)
        for severity in ("error", "warning")
    }
    lines.append(
        f"---\n\n{len(R.RULES)} rules: {counts['error']} errors, {counts['warning']} warnings.\n"
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the file is stale")
    args = parser.parse_args()

    content = render()
    current = TARGET.read_text(encoding="utf-8") if TARGET.is_file() else ""

    if args.check:
        if current != content:
            print(f"ERROR: {TARGET.relative_to(ROOT)} is out of date", file=sys.stderr)
            print(
                "run `python scripts/material/gen_structure_md.py` to regenerate", file=sys.stderr
            )
            return 1
        print("structure.md is up to date")
        return 0

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(content, encoding="utf-8")
    print(f"wrote {TARGET.relative_to(ROOT)} ({len(G.TEMPLATES)} templates, {len(R.RULES)} rules)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
