#!/usr/bin/env python3
"""Generate `references/schemas.md` from the schema and schedule definitions.

Same reasoning as `gen_rules_md.py`: the model writes these files, `verify`
checks them, and a header documented one way but enforced another produces a
document that fails a check the prose said it would pass.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "src"))

from get_fsa_training_done.features.program.core import schedule as S  # noqa: E402
from get_fsa_training_done.features.program.core import schemas as SC  # noqa: E402

TARGET = (
    ROOT
    / "src"
    / "get_fsa_training_done"
    / "payload"
    / "get-fsa-training-done"
    / "references"
    / "program"
    / "schemas.md"
)

HEADER = """# File formats

Every file is UTF-8. CSVs use a comma delimiter, one header row, RFC 4180
quoting, and an **empty cell** rather than a placeholder when there is nothing
to record — "no teaching that day" and "zero hours" are different claims.

Headers are fixed and case-sensitive: they become the workbook's columns, and a
renamed one is not caught at export, it writes the wrong column.

Two of these tables end in a **derived tail** whose width depends on the
programme rather than on this tool: `W1..Wn` for as many weeks as it runs,
`D1..Dm` for as many calendar days, and one column per module in the outcome
mapping. They must run from 1 with no gaps.

<!-- Generated by scripts/program/gen_schemas_md.py from
     src/get_fsa_training_done/features/program/core/{schemas,schedule}.py.
     Do not edit by hand; edit the Python and regenerate. -->
"""

TAIL_NOTES = {
    "W": (
        "one column per week, `W1..Wn`; the cell reads `Mark` in the module's "
        "assessment week and is otherwise empty"
    ),
    "D": (
        "one column per calendar day, `D1..Dm`; a numeric cell is the hours taught "
        "that day, and weekend positions stay empty"
    ),
}


def render() -> str:
    lines = [HEADER, "\n## Tables\n"]
    for schema in SC.ALL_SCHEMAS:
        lines.append(f"### `*_{schema.name}`\n")
        lines.append("Fixed columns, in order:\n")
        lines.append("```")
        lines.append(",".join(schema.fixed))
        lines.append("```\n")
        if schema.index_prefix:
            lines.append(f"Then {TAIL_NOTES[schema.index_prefix]}.\n")
        if schema.module_tail:
            lines.append(
                "Then one column per module code, in the order the module table "
                "lists them; the cell reads `x` where the outcome is delivered.\n"
            )
    lines.append("\n## Delivery types\n")
    lines.append(
        "A closed list. It is also the row order of a syllabus's Time Allocation "
        "table, which the workbook writes as a fixed block.\n"
    )
    for delivery_type in S.DELIVERY_TYPES:
        lines.append(f"- `{delivery_type}`")
    lines.append(f"\nEvery session-plan row uses `{S.TRAINING_FORMAT}` as its training format.\n")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the file is stale")
    args = parser.parse_args()

    content = render()
    current = TARGET.read_text(encoding="utf-8") if TARGET.is_file() else ""

    if args.check:
        if current != content:
            print(f"ERROR: {TARGET.relative_to(ROOT)} is out of date", file=sys.stderr)
            print("run `python scripts/program/gen_schemas_md.py` to regenerate", file=sys.stderr)
            return 1
        print("schemas.md is up to date")
        return 0

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(content, encoding="utf-8")
    print(f"wrote {TARGET.relative_to(ROOT)} ({len(SC.ALL_SCHEMAS)} tables)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
