#!/usr/bin/env python3
"""Generate the programme skill's `references/rules.md` from `core/rules.py`.

The model reads the Markdown; `verify` executes the Python. Written by hand they
drift, and drift here is invisible: if the prose says a session may run 240
minutes while the checker allows 300, the model calibrates to a number nothing
enforces. So the table is generated, and `--check` fails CI when it is stale.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "src"))

from get_fsa_training_done.features.program.core import rules as R  # noqa: E402

TARGET = (
    ROOT
    / "src"
    / "get_fsa_training_done"
    / "payload"
    / "get-fsa-training-done"
    / "references"
    / "program"
    / "rules.md"
)

SCOPES = (
    ("program", "Programme", "The curriculum document and the four CSVs beside it."),
    ("topic", "Topic", "One syllabus and the session plan next to it."),
    ("cross", "Cross-links", "Checks that need the programme and every topic at once."),
)

HEADER = """# Verification rules

Every finding `FSA program verify` reports names the rule that produced it, so a
failure is a lookup here rather than a paragraph to interpret.

**Errors** mean the artifacts contradict each other and the programme cannot be
exported as it stands. **Warnings** mean something looks wrong but may be
deliberate — a capstone really does group a chapter by sprint — so they are
reported and the run still passes. `--strict` promotes them.

Nothing in this table is a constant this tool carries. The module count, the
hour and day totals, the length of a training day, and the number of week and
day columns are all derived from the sources; when a rule mentions a number it
means the number those sources imply.

<!-- Generated by scripts/program/gen_rules_md.py from
     src/get_fsa_training_done/features/program/core/rules.py.
     Do not edit by hand; edit the Python and regenerate. -->
"""


def render() -> str:
    lines = [HEADER]
    for scope, title, blurb in SCOPES:
        rules_in_scope = [rule for rule in R.RULES if rule.scope == scope]
        lines.append(f"\n## {title}\n")
        lines.append(f"{blurb}\n")
        lines.append("| Rule | Severity | Checks |")
        lines.append("|---|---|---|")
        for rule in rules_in_scope:
            lines.append(f"| `{rule.id}` | {rule.severity} | {rule.title} |")
        lines.append("")
        for rule in rules_in_scope:
            lines.append(f"### `{rule.id}` — {rule.title}\n")
            lines.append(f"{rule.rationale}\n")
    counts = {
        severity: sum(1 for r in R.RULES if r.severity == severity)
        for severity in ("error", "warning")
    }
    lines.append(
        f"---\n\n{len(R.RULES)} rules: {counts['error']} errors, {counts['warning']} warnings.\n"
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the file is stale")
    args = parser.parse_args()

    content = render()
    current = TARGET.read_text(encoding="utf-8") if TARGET.is_file() else ""

    if args.check:
        if current != content:
            print(f"ERROR: {TARGET.relative_to(ROOT)} is out of date", file=sys.stderr)
            print("run `python scripts/program/gen_rules_md.py` to regenerate", file=sys.stderr)
            return 1
        print("rules.md is up to date")
        return 0

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(content, encoding="utf-8")
    print(f"wrote {TARGET.relative_to(ROOT)} ({len(R.RULES)} rules)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
